site_name: Open Frannkfurter documentation
repo_url: https://github.com/icobra/OpenFrankfurter
repo_name: icobra/OpenFrankfurter
site_author: iCobra

markdown_extensions:
  - attr_list

nav:
  - "About": index.md
  - Get started:
    - 'get_started/index.md': "Get started"
  - FAQ:
    - 'faq/index.md': "FAQ"
  - Contributing:
    - 'contributing/index.md': "Contributing"

theme:
  name: material
  palette:
    # Create scheme in data-md-color-scheme part of extra.ccs  
    scheme: classic
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github


  features:
    # Add navigation tabs in header
    - navigation.sections
    - navigation.tabs
    - navigation.instant

extra_css:
  - stylesheets/extra.css
